In [7]:
import nibabel as nib
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sb
from scipy import stats
import commands

In [2]:
def get_even_num(num=63):
    runs = []
    evens = []
    j = 0
    for i in range(num):
        if (i != 0) & (i != 2):
            if i % 2 == 0:
                evens.append(str(i))
                j += 1
                if j == 5: 
                    runs.append(evens)
                    evens = []
                    j = 0
    return runs

In [5]:
data_path = "/Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/"
# data_path = "/Users/mriworkshop/Documents/TDCS/code/tdcs_thesis/data/"
save_path = data_path+"raw/"
sub_path_32 = data_path+"external/R21_32_aqueous_2mA/"
sub_path_33 = data_path+"external/R21_33_aqueous_2mA/"
sub_path_34 = data_path+"external/R21_34_aqueous_p2mA/"
sub_path_35 = data_path+"external/R21_35_Cyl_Aqueous/"
sub_path_36 = data_path+"external/R21_36_Cyl_Aqueous/"
sub_path_37 = data_path+"external/R21_37_Cyl_Aqueous/"
sub_path_38 = data_path+"external/R21_38_Cyl_Aqueous/"
#cwd_path = sub_path+"/NIFTI/bmaps_numpy/"
tes = [2.46, 4.61, 7.09, 10.5, 15.0, 20.0, 24.5, 29.0, 33.5, 38.0, 42.5, 47.0]

# 36 to 38
base_runs = get_even_num()
bp = [['6','4'],['10','4'],['6','10']],[['16','14'],['20','14'],['16','20']],[['26','24'],['30','24'],['26','30']],[['36','34'],['40','34'],['36','40']],[['46','44'],['50','44'],['46','50']],[['56','54'],['60','54'],['56','60']]

In [4]:
base_runs

[['4', '6', '8', '10', '12'],
 ['14', '16', '18', '20', '22'],
 ['24', '26', '28', '30', '32'],
 ['34', '36', '38', '40', '42'],
 ['44', '46', '48', '50', '52'],
 ['54', '56', '58', '60', '62']]

In [13]:
bp

([['6', '4'], ['10', '4'], ['6', '10']],
 [['16', '14'], ['20', '14'], ['16', '20']],
 [['26', '24'], ['30', '24'], ['26', '30']],
 [['36', '34'], ['40', '34'], ['36', '40']],
 [['46', '44'], ['50', '44'], ['46', '50']],
 [['56', '54'], ['60', '54'], ['56', '60']])

# Create mask

In [14]:
def create_mask(sub_path, base_runs):
    for m in range(len(base_runs)):
        cwd_path = sub_path+"NIFTI/bmaps_numpy/"
        for n in range(len(base_runs[m])):
            bdir = cwd_path+"base_run_"+base_runs[m][n]+"/"
            print commands.getoutput("fslmaths "+bdir+"4d_fmap_Mean.nii.gz -div "+bdir+"4d_fmap_Mean.nii.gz "+bdir+"mask.nii.gz")
            print commands.getoutput("3dmaskdump -o "+bdir+"/mask.txt -xyz -nozero "+bdir+"mask.nii.gz")

In [18]:
def create_erode_image(sub_path, base_runs, bp, erode = "1"):
    for m in range(len(base_runs)):
        cwd_path = sub_path+"NIFTI/bmaps_numpy/"
        tdir = cwd_path+bp[m][0][0]+"minus"+bp[m][0][1]
        print commands.getoutput("3dmask_tool -input "s+tdir+"/mask.nii.gz -prefix "+tdir+"/mask_erode"+erode+".nii.gz -dilate_result -"+erode)
        print commands.getoutput("fslmaths "+tdir+"/mask_erode"+erode+".nii.gz -mul "+tdir+"/4d_fmap_Mean.nii.gz "+tdir+"/diff_fmap_Mean_erode"+erode+".nii.gz")
        print commands.getoutput("fslmaths "+tdir+"/mask_erode"+erode+".nii.gz -mul "+tdir+"/Bvals.nii "+tdir+"/Bvals_erode"+erode+".nii.gz")
            
        for n in range(len(base_runs[m])):
            bdir = cwd_path+"base_run_"+base_runs[m][n]
            print commands.getoutput("3dmask_tool -input "+bdir+"/mask.nii.gz -prefix "+bdir+"/mask_erode"+erode+".nii.gz -dilate_result -"+erode)
            print commands.getoutput("fslmaths "+bdir+"/mask_erode"+erode+".nii.gz -mul "+bdir+"/4d_fmap_Mean.nii.gz "+bdir+"/diff_fmap_Mean_erode"+erode+".nii.gz")

In [16]:
# 32 and 33
base_runs = [['4', '6', '8', '10', '12'], ['14', '16', '18', '20', '22']]
bp = [['6','4'],['10','4'],['6','10']],[['16','14'],['20','14'],['16','20']]
create_mask(sub_path_32, base_runs)
create_mask(sub_path_33, base_runs)
create_erode_image(sub_path_32, base_runs, bp)
create_erode_image(sub_path_33, base_runs, bp)

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_32_aqueous_2mA/NIFTI/bmaps_numpy/base_run_4//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_32_aqueous_2mA/NIFTI/bmaps_numpy/base_run_6//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_32_aqueous_2mA/NIFTI/bmaps_numpy/base_run_8//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_32_aqueous_2mA/NIFTI/bmaps_numpy/base_run_10//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_32_aqueous_2mA/NIFTI/bmaps_numpy/base_run_12//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_32_aqueous_2mA/NIFTI/bmaps_numpy/base_run_14//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_32_aqueous_2mA/NIFTI/bmaps_numpy/base_run_16//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_32_aqueous_2mA/NIFTI/bmaps_numpy/base_run_18//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_32_aqueous_2mA/NIFTI/bmaps_numpy/base_run_20//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_32_aqueous_2mA/NIFTI/bmaps_numpy/base_run_22//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_33_aqueous_2mA/NIFTI/bmaps_numpy/base_run_4//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_33_aqueous_2mA/NIFTI/bmaps_numpy/base_run_6//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_33_aqueous_2mA/NIFTI/bmaps_numpy/base_run_8//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_33_aqueous_2mA/NIFTI/bmaps_numpy/base_run_10//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_33_aqueous_2mA/NIFTI/bmaps_numpy/base_run_12//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_33_aqueous_2mA/NIFTI/bmaps_numpy/base_run_14//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_33_aqueous_2mA/NIFTI/bmaps_numpy/base_run_16//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_33_aqueous_2mA/NIFTI/bmaps_numpy/base_run_18//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_33_aqueous_2mA/NIFTI/bmaps_numpy/base_run_20//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_33_aqueous_2mA/NIFTI/bmaps_numpy/base_run_22//mask.txt already exists!
** Program compile date = Jun 24 2022
++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34832 survived, 145392 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_32_aqueous_2mA/NIFTI/bmaps_numpy/6minus4//mask_erode1.nii.gz


++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34858 survived, 145366 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_32_aqueous_2mA/NIFTI/bmaps_numpy/base_run_4//mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34862 survived, 145362 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_32_aqueous_2mA/NIFTI/bmaps_numpy/base_run_6//mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34860 survived, 145364 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_32_aqueous_2mA/NIFTI/bmaps_numpy/base_run_8//mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34857 survived, 145367 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_32_aqueous_2mA/NIFTI/bmaps_numpy/base_run_10//mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34858 survived, 145366 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_32_aqueous_2mA/NIFTI/bmaps_numpy/base_run_12//mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34832 survived, 145392 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_32_aqueous_2mA/NIFTI/bmaps_numpy/16minus14//mask_erode1.nii.gz


++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34859 survived, 145365 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_32_aqueous_2mA/NIFTI/bmaps_numpy/base_run_14//mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34862 survived, 145362 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_32_aqueous_2mA/NIFTI/bmaps_numpy/base_run_16//mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34858 survived, 145366 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_32_aqueous_2mA/NIFTI/bmaps_numpy/base_run_18//mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34863 survived, 145361 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_32_aqueous_2mA/NIFTI/bmaps_numpy/base_run_20//mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34861 survived, 145363 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_32_aqueous_2mA/NIFTI/bmaps_numpy/base_run_22//mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34899 survived, 145325 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_33_aqueous_2mA/NIFTI/bmaps_numpy/6minus4//mask_erode1.nii.gz


++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34926 survived, 145298 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_33_aqueous_2mA/NIFTI/bmaps_numpy/base_run_4//mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34929 survived, 145295 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_33_aqueous_2mA/NIFTI/bmaps_numpy/base_run_6//mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34924 survived, 145300 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_33_aqueous_2mA/NIFTI/bmaps_numpy/base_run_8//mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34924 survived, 145300 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_33_aqueous_2mA/NIFTI/bmaps_numpy/base_run_10//mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34923 survived, 145301 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_33_aqueous_2mA/NIFTI/bmaps_numpy/base_run_12//mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34895 survived, 145329 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_33_aqueous_2mA/NIFTI/bmaps_numpy/16minus14//mask_erode1.nii.gz


++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34926 survived, 145298 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_33_aqueous_2mA/NIFTI/bmaps_numpy/base_run_14//mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34927 survived, 145297 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_33_aqueous_2mA/NIFTI/bmaps_numpy/base_run_16//mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34923 survived, 145301 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_33_aqueous_2mA/NIFTI/bmaps_numpy/base_run_18//mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34925 survived, 145299 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_33_aqueous_2mA/NIFTI/bmaps_numpy/base_run_20//mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34926 survived, 145298 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_33_aqueous_2mA/NIFTI/bmaps_numpy/base_run_22//mask_erode1.nii.gz

In [17]:
# 34
base_runs = [['4', '6', '8', '10', '12']]
bp = [['6','4'],['10','4'],['6','10']],
create_mask(sub_path_34, base_runs)
create_erode_image(sub_path_34, base_runs, bp)

++ 3dmaskdump: AFNI version=AFNI_22.1.14 (Jun 24 2022) [64-bit]
++ 180224 voxels in the entire dataset (no mask)

++ 3dmaskdump: AFNI version=AFNI_22.1.14 (Jun 24 2022) [64-bit]
++ 180224 voxels in the entire dataset (no mask)

++ 3dmaskdump: AFNI version=AFNI_22.1.14 (Jun 24 2022) [64-bit]
++ 180224 voxels in the entire dataset (no mask)

++ 3dmaskdump: AFNI version=AFNI_22.1.14 (Jun 24 2022) [64-bit]
++ 180224 voxels in the entire dataset (no mask)

++ 3dmaskdump: AFNI version=AFNI_22.1.14 (Jun 24 2022) [64-bit]
++ 180224 voxels in the entire dataset (no mask)
++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34469 survived, 145755 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_34_aqueous_p2mA/NIFTI/bmaps_numpy/6minus4//mask_erode1.nii.gz


++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34495 survived, 145729 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_34_aqueous_p2mA/NIFTI/bmaps_numpy/base_run_4//mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34492 survived, 145732 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_34_aqueous_p2mA/NIFTI/bmaps_numpy/base_run_6//mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34493 survived, 145731 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_34_aqueous_p2mA/NIFTI/bmaps_numpy/base_run_8//mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34494 survived, 145730 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_34_aqueous_p2mA/NIFTI/bmaps_numpy/base_run_10//mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34496 survived, 145728 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_34_aqueous_p2mA/NIFTI/bmaps_numpy/base_run_12//mask_erode1.nii.gz

In [19]:
# 35
base_runs = [['4', '6', '8', '10', '12'],
 ['14', '16', '18', '20', '22'],
 ['24', '26', '28', '30', '32'],
 ['34', '36', '38', '40', '42'],
 ['44', '46', '48', '50', '52']]
bp = [['6','4'],['10','4'],['6','10']],[['16','14'],['20','14'],['16','20']],[['26','24'],['30','24'],['26','30']],[['36','34'],['40','34'],['36','40']],[['46','44'],['50','44'],['46','50']]
create_mask(sub_path_35, base_runs)
create_erode_image(sub_path_35, base_runs, bp)

++ 3dmaskdump: AFNI version=AFNI_22.1.14 (Jun 24 2022) [64-bit]
++ 180224 voxels in the entire dataset (no mask)

++ 3dmaskdump: AFNI version=AFNI_22.1.14 (Jun 24 2022) [64-bit]
++ 180224 voxels in the entire dataset (no mask)

++ 3dmaskdump: AFNI version=AFNI_22.1.14 (Jun 24 2022) [64-bit]
++ 180224 voxels in the entire dataset (no mask)

++ 3dmaskdump: AFNI version=AFNI_22.1.14 (Jun 24 2022) [64-bit]
++ 180224 voxels in the entire dataset (no mask)

++ 3dmaskdump: AFNI version=AFNI_22.1.14 (Jun 24 2022) [64-bit]
++ 180224 voxels in the entire dataset (no mask)

++ 3dmaskdump: AFNI version=AFNI_22.1.14 (Jun 24 2022) [64-bit]
++ 180224 voxels in the entire dataset (no mask)

++ 3dmaskdump: AFNI version=AFNI_22.1.14 (Jun 24 2022) [64-bit]
++ 180224 voxels in the entire dataset (no mask)

++ 3dmaskdump: AFNI version=AFNI_22.1.14 (Jun 24 2022) [64-bit]
++ 180224 voxels in the entire dataset (no mask)

++ 3dmaskdump: AFNI version=AFNI_22.1.14 (Jun 24 2022) [64-bit]
++ 180224 voxels in the entire dataset (no mask)

++ 3dmaskdump: AFNI version=AFNI_22.1.14 (Jun 24 2022) [64-bit]
++ 180224 voxels in the entire dataset (no mask)

++ 3dmaskdump: AFNI version=AFNI_22.1.14 (Jun 24 2022) [64-bit]
++ 180224 voxels in the entire dataset (no mask)

++ 3dmaskdump: AFNI version=AFNI_22.1.14 (Jun 24 2022) [64-bit]
++ 180224 voxels in the entire dataset (no mask)

++ 3dmaskdump: AFNI version=AFNI_22.1.14 (Jun 24 2022) [64-bit]
++ 180224 voxels in the entire dataset (no mask)

++ 3dmaskdump: AFNI version=AFNI_22.1.14 (Jun 24 2022) [64-bit]
++ 180224 voxels in the entire dataset (no mask)

++ 3dmaskdump: AFNI version=AFNI_22.1.14 (Jun 24 2022) [64-bit]
++ 180224 voxels in the entire dataset (no mask)

++ 3dmaskdump: AFNI version=AFNI_22.1.14 (Jun 24 2022) [64-bit]
++ 180224 voxels in the entire dataset (no mask)

++ 3dmaskdump: AFNI version=AFNI_22.1.14 (Jun 24 2022) [64-bit]
++ 180224 voxels in the entire dataset (no mask)

++ 3dmaskdump: AFNI version=AFNI_22.1.14 (Jun 24 2022) [64-bit]
++ 180224 voxels in the entire dataset (no mask)

++ 3dmaskdump: AFNI version=AFNI_22.1.14 (Jun 24 2022) [64-bit]
++ 180224 voxels in the entire dataset (no mask)

++ 3dmaskdump: AFNI version=AFNI_22.1.14 (Jun 24 2022) [64-bit]
++ 180224 voxels in the entire dataset (no mask)

++ 3dmaskdump: AFNI version=AFNI_22.1.14 (Jun 24 2022) [64-bit]
++ 180224 voxels in the entire dataset (no mask)

++ 3dmaskdump: AFNI version=AFNI_22.1.14 (Jun 24 2022) [64-bit]
++ 180224 voxels in the entire dataset (no mask)

++ 3dmaskdump: AFNI version=AFNI_22.1.14 (Jun 24 2022) [64-bit]
++ 180224 voxels in the entire dataset (no mask)

++ 3dmaskdump: AFNI version=AFNI_22.1.14 (Jun 24 2022) [64-bit]
++ 180224 voxels in the entire dataset (no mask)

++ 3dmaskdump: AFNI version=AFNI_22.1.14 (Jun 24 2022) [64-bit]
++ 180224 voxels in the entire dataset (no mask)
++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 28330 survived, 151894 were zero
++ writing result mask_erode1.nii.gz...
** ERROR: output dataset name 'mask_erode1.nii.gz' conflicts with existing file
** ERROR: dataset NOT written to disk!


++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 28342 survived, 151882 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_35_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_4/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 28345 survived, 151879 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_35_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_6/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 28345 survived, 151879 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_35_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_8/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 28345 survived, 151879 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_35_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_10/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 28345 survived, 151879 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_35_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_12/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 28331 survived, 151893 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_35_Cyl_Aqueous/NIFTI/bmaps_numpy/16minus14/mask_erode1.nii.gz


++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 28343 survived, 151881 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_35_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_14/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 28345 survived, 151879 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_35_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_16/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 28347 survived, 151877 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_35_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_18/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 28343 survived, 151881 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_35_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_20/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 28346 survived, 151878 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_35_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_22/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 28334 survived, 151890 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_35_Cyl_Aqueous/NIFTI/bmaps_numpy/26minus24/mask_erode1.nii.gz


++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 28343 survived, 151881 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_35_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_24/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 28346 survived, 151878 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_35_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_26/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 28347 survived, 151877 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_35_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_28/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 28342 survived, 151882 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_35_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_30/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 28343 survived, 151881 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_35_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_32/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 28331 survived, 151893 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_35_Cyl_Aqueous/NIFTI/bmaps_numpy/36minus34/mask_erode1.nii.gz


++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 28346 survived, 151878 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_35_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_34/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 28344 survived, 151880 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_35_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_36/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 28344 survived, 151880 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_35_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_38/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 28344 survived, 151880 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_35_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_40/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 28345 survived, 151879 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_35_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_42/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 28330 survived, 151894 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_35_Cyl_Aqueous/NIFTI/bmaps_numpy/46minus44/mask_erode1.nii.gz


++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 28343 survived, 151881 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_35_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_44/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 28343 survived, 151881 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_35_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_46/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 28344 survived, 151880 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_35_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_48/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 28343 survived, 151881 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_35_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_50/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 28344 survived, 151880 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_35_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_52/mask_erode1.nii.gz

In [20]:
# 36 to 38
base_runs = get_even_num()
bp = [['6','4'],['10','4'],['6','10']],[['16','14'],['20','14'],['16','20']],[['26','24'],['30','24'],['26','30']],[['36','34'],['40','34'],['36','40']],[['46','44'],['50','44'],['46','50']],[['56','54'],['60','54'],['56','60']]
create_mask(sub_path_36, base_runs)
create_mask(sub_path_37, base_runs)
create_mask(sub_path_38, base_runs)
create_erode_image(sub_path_36, base_runs, bp)
create_erode_image(sub_path_37, base_runs, bp)
create_erode_image(sub_path_38, base_runs, bp)

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_4//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_6//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_8//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_10//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_12//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_14//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_16//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_18//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_20//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_22//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_24//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_26//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_28//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_30//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_32//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_34//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_36//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_38//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_40//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_42//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_44//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_46//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_48//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_50//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_52//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_54//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_56//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_58//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_60//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_62//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_4//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_6//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_8//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_10//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_12//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_14//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_16//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_18//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_20//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_22//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_24//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_26//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_28//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_30//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_32//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_34//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_36//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_38//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_40//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_42//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_44//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_46//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_48//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_50//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_52//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_54//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_56//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_58//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_60//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_62//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_4//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_6//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_8//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_10//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_12//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_14//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_16//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_18//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_20//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_22//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_24//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_26//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_28//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_30//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_32//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_34//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_36//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_38//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_40//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_42//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_44//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_46//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_48//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_50//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_52//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_54//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_56//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_58//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_60//mask.txt already exists!
** Program compile date = Jun 24 2022

** FATAL ERROR: file /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_62//mask.txt already exists!
** Program compile date = Jun 24 2022
++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 33992 survived, 146232 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/6minus4/mask_erode1.nii.gz


++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34014 survived, 146210 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_4/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34016 survived, 146208 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_6/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34015 survived, 146209 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_8/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34018 survived, 146206 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_10/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34017 survived, 146207 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_12/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 33982 survived, 146242 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/16minus14/mask_erode1.nii.gz


++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34020 survived, 146204 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_14/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34023 survived, 146201 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_16/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34023 survived, 146201 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_18/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34017 survived, 146207 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_20/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34016 survived, 146208 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_22/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 33979 survived, 146245 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/26minus24/mask_erode1.nii.gz


++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34020 survived, 146204 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_24/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34020 survived, 146204 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_26/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34024 survived, 146200 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_28/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34014 survived, 146210 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_30/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34020 survived, 146204 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_32/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 33983 survived, 146241 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/36minus34/mask_erode1.nii.gz


++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34019 survived, 146205 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_34/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34020 survived, 146204 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_36/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34016 survived, 146208 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_38/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34016 survived, 146208 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_40/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34020 survived, 146204 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_42/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 33986 survived, 146238 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/46minus44/mask_erode1.nii.gz


++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34020 survived, 146204 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_44/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34022 survived, 146202 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_46/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34020 survived, 146204 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_48/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34019 survived, 146205 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_50/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34024 survived, 146200 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_52/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 33988 survived, 146236 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/56minus54/mask_erode1.nii.gz


++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34021 survived, 146203 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_54/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34026 survived, 146198 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_56/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34016 survived, 146208 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_58/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34021 survived, 146203 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_60/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34025 survived, 146199 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_62/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34847 survived, 145377 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/6minus4/mask_erode1.nii.gz


++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34888 survived, 145336 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_4/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34892 survived, 145332 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_6/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34895 survived, 145329 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_8/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34890 survived, 145334 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_10/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34889 survived, 145335 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_12/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34850 survived, 145374 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/16minus14/mask_erode1.nii.gz


++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34890 survived, 145334 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_14/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34890 survived, 145334 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_16/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34894 survived, 145330 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_18/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34890 survived, 145334 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_20/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34888 survived, 145336 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_22/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34852 survived, 145372 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/26minus24/mask_erode1.nii.gz


++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34889 survived, 145335 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_24/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34894 survived, 145330 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_26/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34894 survived, 145330 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_28/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34890 survived, 145334 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_30/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34889 survived, 145335 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_32/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34854 survived, 145370 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/36minus34/mask_erode1.nii.gz


++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34891 survived, 145333 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_34/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34892 survived, 145332 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_36/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34894 survived, 145330 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_38/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34891 survived, 145333 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_40/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34889 survived, 145335 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_42/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34848 survived, 145376 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/46minus44/mask_erode1.nii.gz


++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34891 survived, 145333 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_44/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34892 survived, 145332 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_46/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34891 survived, 145333 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_48/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34892 survived, 145332 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_50/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34887 survived, 145337 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_52/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34851 survived, 145373 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/56minus54/mask_erode1.nii.gz


++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34891 survived, 145333 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_54/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34894 survived, 145330 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_56/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34890 survived, 145334 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_58/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34892 survived, 145332 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_60/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34890 survived, 145334 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_62/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34853 survived, 145371 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/6minus4/mask_erode1.nii.gz


++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34903 survived, 145321 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_4/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34904 survived, 145320 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_6/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34901 survived, 145323 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_8/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34899 survived, 145325 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_10/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34898 survived, 145326 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_12/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34859 survived, 145365 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/16minus14/mask_erode1.nii.gz


++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34902 survived, 145322 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_14/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34904 survived, 145320 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_16/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34903 survived, 145321 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_18/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34901 survived, 145323 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_20/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34899 survived, 145325 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_22/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34857 survived, 145367 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/26minus24/mask_erode1.nii.gz


++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34902 survived, 145322 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_24/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34903 survived, 145321 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_26/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34902 survived, 145322 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_28/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34902 survived, 145322 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_30/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34898 survived, 145326 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_32/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34857 survived, 145367 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/36minus34/mask_erode1.nii.gz


++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34903 survived, 145321 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_34/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34904 survived, 145320 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_36/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34903 survived, 145321 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_38/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34902 survived, 145322 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_40/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34900 survived, 145324 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_42/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34858 survived, 145366 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/46minus44/mask_erode1.nii.gz


++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34903 survived, 145321 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_44/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34903 survived, 145321 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_46/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34903 survived, 145321 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_48/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34900 survived, 145324 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_50/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34897 survived, 145327 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_52/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34858 survived, 145366 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/56minus54/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34900 survived, 145324 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_54/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34903 survived, 145321 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_56/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34902 survived, 145322 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_58/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34899 survived, 145325 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_60/mask_erode1.nii.gz

++ no -frac option: defaulting to -union
++ processing 1 input dataset(s), NN=2...
++ padding all datasets by 0 (for dilations)
++ frac 0 over 1 volumes gives min count 0
++ voxel limits: 0 clipped, 34900 survived, 145324 were zero
++ writing result mask_erode1.nii.gz...
++ Output dataset /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/NIFTI/bmaps_numpy/base_run_62/mask_erode1.nii.gz

# Extract Data

## 1. fmap mean of 5 runs (erode)

In [21]:
def extract_mean(sub_path, experiment):
    print(sub_path)
    cwd_path = sub_path+"/NIFTI/bmaps_numpy/"
    result = pd.DataFrame()
    for m in range(len(base_runs)):   
        tdir = cwd_path+bp[m][0][0]+"minus"+bp[m][0][1]+"/"
        theory_img = nib.load(tdir+"Bvals_erode1.nii.gz")
        theory_data = theory_img.get_data()
        sp = theory_data.shape
        b_data = []

        for i in range(sp[0]):
            for j in range(sp[1]):
                for k in range(sp[2]):
                    b_data.append([experiment, m+1, i, j, k, theory_data[i][j][k]])

        b_df = pd.DataFrame(b_data, columns=['exp', 'mini_exp', 'i', 'j', 'k', 'theory'])

        df = pd.DataFrame()
        for n in range(len(base_runs[m])):
            bdir = cwd_path+"base_run_"+base_runs[m][n]+"/"
            print(base_runs[m][n])

            new_data = []      
            fmap_img = nib.load(bdir+"diff_fmap_Mean_erode1.nii.gz")
            fmap_data = fmap_img.get_data()
            sp = fmap_data.shape            
            col = "mean"+str(n)

            for i in range(sp[0]):
                for j in range(sp[1]):
                    for k in range(sp[2]):
                        new_data.append([experiment, m+1, i, j, k, fmap_data[i][j][k]])

            new_df = pd.DataFrame(new_data, columns=['exp', 'mini_exp', 'i', 'j', 'k', col])
            if n == 0:
                df = new_df
            else:
                df = df.merge(new_df, on=['exp', 'mini_exp', 'i', 'j', 'k'], sort=False)


        df = df.merge(b_df, on=['exp','mini_exp', 'i', 'j', 'k'], sort=False)
        result = result.append(df, ignore_index=True)
    return result

In [22]:
# 32 and 33
base_runs = [['4', '6', '8', '10', '12'], ['14', '16', '18', '20', '22']]
bp = [['6','4'],['10','4'],['6','10']],[['16','14'],['20','14'],['16','20']]

In [23]:
result_32 = extract_mean(sub_path_32, '32')
result_33 = extract_mean(sub_path_33, '33')

/Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_32_aqueous_2mA/
4
6
8
10
12
14
16
18
20
22
/Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_33_aqueous_2mA/
4
6
8
10
12
14
16
18
20
22

In [24]:
# 34
base_runs = [['4', '6', '8', '10', '12']]
bp = [['6','4'],['10','4'],['6','10']],

In [25]:
result_34 = extract_mean(sub_path_34, '34')

/Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_34_aqueous_p2mA/
4
6
8
10
12

In [26]:
# 35
base_runs = [['4', '6', '8', '10', '12'],
 ['14', '16', '18', '20', '22'],
 ['24', '26', '28', '30', '32'],
 ['34', '36', '38', '40', '42'],
 ['44', '46', '48', '50', '52']]
bp = [['6','4'],['10','4'],['6','10']],[['16','14'],['20','14'],['16','20']],[['26','24'],['30','24'],['26','30']],[['36','34'],['40','34'],['36','40']],[['46','44'],['50','44'],['46','50']]

In [27]:
result_35 = extract_mean(sub_path_35, '35')

/Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_35_Cyl_Aqueous/
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52

In [28]:
# 36 to 38
base_runs = get_even_num()
bp = [['6','4'],['10','4'],['6','10']],[['16','14'],['20','14'],['16','20']],[['26','24'],['30','24'],['26','30']],[['36','34'],['40','34'],['36','40']],[['46','44'],['50','44'],['46','50']],[['56','54'],['60','54'],['56','60']]

In [29]:
result_36 = extract_mean(sub_path_36, '36')
result_37 = extract_mean(sub_path_37, '37')
result_38 = extract_mean(sub_path_38, '38')

/Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous/
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
/Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
/Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62

In [30]:
print(result_32.shape)
print(result_33.shape)
print(result_34.shape)
print(result_35.shape)
print(result_36.shape)
print(result_37.shape)
print(result_38.shape)

(360448, 11)
(360448, 11)
(180224, 11)
(901120, 11)
(1081344, 11)
(1081344, 11)
(1081344, 11)

In [31]:
result = result_36.append(result_37, ignore_index=True)
result = result.append(result_38, ignore_index=True)
result = result.append(result_32, ignore_index=True)
result = result.append(result_33, ignore_index=True)
result = result.append(result_34, ignore_index=True)
result = result.append(result_35, ignore_index=True)
result

        exp  mini_exp   i   j   k  mean0  mean1  mean2  mean3  mean4  theory
0        36         1   0   0   0    0.0    0.0    0.0    0.0    0.0     0.0
1        36         1   0   0   1    0.0    0.0    0.0    0.0    0.0     0.0
2        36         1   0   0   2    0.0    0.0    0.0    0.0    0.0     0.0
3        36         1   0   0   3    0.0    0.0    0.0    0.0    0.0     0.0
4        36         1   0   0   4    0.0    0.0    0.0    0.0    0.0     0.0
5        36         1   0   0   5    0.0    0.0    0.0    0.0    0.0     0.0
6        36         1   0   0   6    0.0    0.0    0.0    0.0    0.0     0.0
7        36         1   0   0   7    0.0    0.0    0.0    0.0    0.0     0.0
8        36         1   0   0   8    0.0    0.0    0.0    0.0    0.0     0.0
9        36         1   0   0   9    0.0    0.0    0.0    0.0    0.0     0.0
10       36         1   0   0  10    0.0    0.0    0.0    0.0    0.0     0.0
11       36         1   0   0  11    0.0    0.0    0.0    0.0    0.0     0.0
12       36         1   0   0  12    0.0    0.0    0.0    0.0    0.0     0.0
13       36         1   0   0  13    0.0    0.0    0.0    0.0    0.0     0.0
14       36         1   0   0  14    0.0    0.0    0.0    0.0    0.0     0.0
15       36         1   0   0  15    0.0    0.0    0.0    0.0    0.0     0.0
16       36         1   0   0  16    0.0    0.0    0.0    0.0    0.0     0.0
17       36         1   0   0  17    0.0    0.0    0.0    0.0    0.0     0.0
18       36         1   0   0  18    0.0    0.0    0.0    0.0    0.0     0.0
19       36         1   0   0  19    0.0    0.0    0.0    0.0    0.0     0.0
20       36         1   0   0  20    0.0    0.0    0.0    0.0    0.0     0.0
21       36         1   0   0  21    0.0    0.0    0.0    0.0    0.0     0.0
22       36         1   0   0  22    0.0    0.0    0.0    0.0    0.0     0.0
23       36         1   0   0  23    0.0    0.0    0.0    0.0    0.0     0.0
24       36         1   0   0  24    0.0    0.0    0.0    0.0    0.0     0.0
25       36         1   0   0  25    0.0    0.0    0.0    0.0    0.0     0.0
26       36         1   0   0  26    0.0    0.0    0.0    0.0    0.0     0.0
27       36         1   0   0  27    0.0    0.0    0.0    0.0    0.0     0.0
28       36         1   0   0  28    0.0    0.0    0.0    0.0    0.0     0.0
29       36         1   0   0  29    0.0    0.0    0.0    0.0    0.0     0.0
...      ..       ...  ..  ..  ..    ...    ...    ...    ...    ...     ...
5046242  35         5  43  63  34    0.0    0.0    0.0    0.0    0.0     0.0
5046243  35         5  43  63  35    0.0    0.0    0.0    0.0    0.0     0.0
5046244  35         5  43  63  36    0.0    0.0    0.0    0.0    0.0     0.0
5046245  35         5  43  63  37    0.0    0.0    0.0    0.0    0.0     0.0
5046246  35         5  43  63  38    0.0    0.0    0.0    0.0    0.0     0.0
5046247  35         5  43  63  39    0.0    0.0    0.0    0.0    0.0     0.0
5046248  35         5  43  63  40    0.0    0.0    0.0    0.0    0.0     0.0
5046249  35         5  43  63  41    0.0    0.0    0.0    0.0    0.0     0.0
5046250  35         5  43  63  42    0.0    0.0    0.0    0.0    0.0     0.0
5046251  35         5  43  63  43    0.0    0.0    0.0    0.0    0.0     0.0
5046252  35         5  43  63  44    0.0    0.0    0.0    0.0    0.0     0.0
5046253  35         5  43  63  45    0.0    0.0    0.0    0.0    0.0     0.0
5046254  35         5  43  63  46    0.0    0.0    0.0    0.0    0.0     0.0
5046255  35         5  43  63  47    0.0    0.0    0.0    0.0    0.0     0.0
5046256  35         5  43  63  48    0.0    0.0    0.0    0.0    0.0     0.0
5046257  35         5  43  63  49    0.0    0.0    0.0    0.0    0.0     0.0
5046258  35         5  43  63  50    0.0    0.0    0.0    0.0    0.0     0.0
5046259  35         5  43  63  51    0.0    0.0    0.0    0.0    0.0     0.0
5046260  35         5  43  63  52    0.0    0.0    0.0    0.0    0.0     0.0
5046261  35         5  43  63  53    0.0    0.0    0.0    0.0    0.0     0.0
5046262  35         5  43  63  54    0.0    0.0    0.0    0.0    0.0     0.0
5046263  35         5  43  63  55    0.0    0.0    0.0    0.0    0.0     0.0
5046264  35         5  43  63  56    0.0    0.0    0.0    0.0    0.0     0.0
5046265  35         5  43  63  57    0.0    0.0    0.0    0.0    0.0     0.0
5046266  35         5  43  63  58    0.0    0.0    0.0    0.0    0.0     0.0
5046267  35         5  43  63  59    0.0    0.0    0.0    0.0    0.0     0.0
5046268  35         5  43  63  60    0.0    0.0    0.0    0.0    0.0     0.0
5046269  35         5  43  63  61    0.0    0.0    0.0    0.0    0.0     0.0
5046270  35         5  43  63  62    0.0    0.0    0.0    0.0    0.0     0.0
5046271  35         5  43  63  63    0.0    0.0    0.0    0.0    0.0     0.0

[5046272 rows x 11 columns]

In [32]:
result.shape

(5046272, 11)

In [33]:
result_32[(result_32['i']==31) & (result_32['j']==31) & (result_32['k']==31)]

,exp,mini_exp,i,j,k,mean0,mean1,mean2,mean3,mean4,theory
128991,32,1,31,31,31,557.953796,581.584106,534.349670,497.107605,514.994507,43.305984
309215,32,2,31,31,31,571.918640,613.776978,577.935974,542.774048,581.564697,43.305984

In [34]:
np.savetxt(save_path+"fmap_mean_erode.txt", result.values, fmt="%s")