In [1]:
import nibabel as nib
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sb
from scipy import stats

In [2]:
def get_even_num(num=63):
    runs = []
    evens = []
    j = 0
    for i in range(num):
        if (i != 0) & (i != 2):
            if i % 2 == 0:
                evens.append(str(i))
                j += 1
                if j == 5: 
                    runs.append(evens)
                    evens = []
                    j = 0
    return runs

In [3]:
data_path = "/Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/"
# data_path = "/Users/mriworkshop/Documents/TDCS/code/tdcs_thesis/data/"
save_path = data_path+"raw/"
sub_path_32 = data_path+"external/R21_32_aqueous_2mA/"
sub_path_33 = data_path+"external/R21_33_aqueous_2mA/"
sub_path_34 = data_path+"external/R21_34_aqueous_p2mA/"
sub_path_35 = data_path+"external/R21_35_Cyl_Aqueous/"
sub_path_36 = data_path+"external/R21_36_Cyl_Aqueous/"
sub_path_37 = data_path+"external/R21_37_Cyl_Aqueous/"
sub_path_38 = data_path+"external/R21_38_Cyl_Aqueous/"
sub_path_39 = data_path+"external/R21_39_Cyl_Aqueous/"
sub_path_40 = data_path+"external/R21_40_Sphere/"
#cwd_path = sub_path+"/NIFTI/bmaps_numpy/"
tes = [2.46, 4.61, 7.09, 10.5, 15.0, 20.0, 24.5, 29.0, 33.5, 38.0, 42.5, 47.0]

# Besides 39
base_runs = get_even_num()
bp = [['6','4'],['10','4'],['6','10']],[['16','14'],['20','14'],['16','20']],[['26','24'],['30','24'],['26','30']],[['36','34'],['40','34'],['36','40']],[['46','44'],['50','44'],['46','50']],[['56','54'],['60','54'],['56','60']]

# 39
#base_runs = get_even_num()
#bp = [['6','4'],['10','4'],['6','10']],[['16','14'],['20','14'],['16','20']],[['26','24'],['30','24'],['26','30']],[['36','34'],['40','34'],['36','40']],[['46','44'],['50','44'],['46','50']],[['58','56'],['62','56'],['58','62']]

In [4]:
base_runs

[['4', '6', '8', '10', '12'],
 ['14', '16', '18', '20', '22'],
 ['24', '26', '28', '30', '32'],
 ['34', '36', '38', '40', '42'],
 ['44', '46', '48', '50', '52'],
 ['54', '56', '58', '60', '62']]

In [5]:
bp

([['6', '4'], ['10', '4'], ['6', '10']],
 [['16', '14'], ['20', '14'], ['16', '20']],
 [['26', '24'], ['30', '24'], ['26', '30']],
 [['36', '34'], ['40', '34'], ['36', '40']],
 [['46', '44'], ['50', '44'], ['46', '50']],
 [['56', '54'], ['60', '54'], ['56', '60']])

# Extract Data

## 1. fmap mean of 5 runs

In [14]:
def extract_mean(sub_path, experiment):
    print(sub_path)
    cwd_path = sub_path+"/NIFTI/bmaps_numpy/"
    result = pd.DataFrame()
    for m in range(len(base_runs)):   
#         tdir = cwd_path+bp[m][0][0]+"minus"+bp[m][0][1]+"/"
#         theory_img = nib.load(tdir+"Bvals.nii")
#         theory_data = theory_img.get_data()
#         sp = theory_data.shape
#         b_data = []

#         for i in range(sp[0]):
#             for j in range(sp[1]):
#                 for k in range(sp[2]):
#                     b_data.append([experiment, m+1, i, j, k, theory_data[i][j][k]])

#         b_df = pd.DataFrame(b_data, columns=['exp', 'mini_exp', 'i', 'j', 'k', 'theory'])

        df = pd.DataFrame()
        for n in range(len(base_runs[m])):
            bdir = cwd_path+"base_run_"+base_runs[m][n]+"/"
            print(base_runs[m][n])

            new_data = []      
            fmap_img = nib.load(bdir+"4d_fmap_Mean.nii.gz")
            fmap_data = fmap_img.get_data()
            sp = fmap_data.shape            
            col = "mean"+str(n)

            for i in range(sp[0]):
                for j in range(sp[1]):
                    for k in range(sp[2]):
                        new_data.append([experiment, m+1, i, j, k, fmap_data[i][j][k]])

            new_df = pd.DataFrame(new_data, columns=['exp', 'mini_exp', 'i', 'j', 'k', col])
            if n == 0:
                df = new_df
            else:
                df = df.merge(new_df, on=['exp', 'mini_exp', 'i', 'j', 'k'], sort=False)


#         df = df.merge(b_df, on=['exp','mini_exp', 'i', 'j', 'k'], sort=False)
        result = result.append(df, ignore_index=True)
    return result

In [15]:
result_40 = extract_mean(sub_path_40, '40')

/Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_40_Sphere/
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62

In [16]:
print(result_40.shape)

(1081344, 10)

In [17]:
result_40

        exp  mini_exp   i   j   k  mean0  mean1  mean2  mean3  mean4
0        40         1   0   0   0    0.0    0.0    0.0    0.0    0.0
1        40         1   0   0   1    0.0    0.0    0.0    0.0    0.0
2        40         1   0   0   2    0.0    0.0    0.0    0.0    0.0
3        40         1   0   0   3    0.0    0.0    0.0    0.0    0.0
4        40         1   0   0   4    0.0    0.0    0.0    0.0    0.0
5        40         1   0   0   5    0.0    0.0    0.0    0.0    0.0
6        40         1   0   0   6    0.0    0.0    0.0    0.0    0.0
7        40         1   0   0   7    0.0    0.0    0.0    0.0    0.0
8        40         1   0   0   8    0.0    0.0    0.0    0.0    0.0
9        40         1   0   0   9    0.0    0.0    0.0    0.0    0.0
10       40         1   0   0  10    0.0    0.0    0.0    0.0    0.0
11       40         1   0   0  11    0.0    0.0    0.0    0.0    0.0
12       40         1   0   0  12    0.0    0.0    0.0    0.0    0.0
13       40         1   0   0  13    0.0    0.0    0.0    0.0    0.0
14       40         1   0   0  14    0.0    0.0    0.0    0.0    0.0
15       40         1   0   0  15    0.0    0.0    0.0    0.0    0.0
16       40         1   0   0  16    0.0    0.0    0.0    0.0    0.0
17       40         1   0   0  17    0.0    0.0    0.0    0.0    0.0
18       40         1   0   0  18    0.0    0.0    0.0    0.0    0.0
19       40         1   0   0  19    0.0    0.0    0.0    0.0    0.0
20       40         1   0   0  20    0.0    0.0    0.0    0.0    0.0
21       40         1   0   0  21    0.0    0.0    0.0    0.0    0.0
22       40         1   0   0  22    0.0    0.0    0.0    0.0    0.0
23       40         1   0   0  23    0.0    0.0    0.0    0.0    0.0
24       40         1   0   0  24    0.0    0.0    0.0    0.0    0.0
25       40         1   0   0  25    0.0    0.0    0.0    0.0    0.0
26       40         1   0   0  26    0.0    0.0    0.0    0.0    0.0
27       40         1   0   0  27    0.0    0.0    0.0    0.0    0.0
28       40         1   0   0  28    0.0    0.0    0.0    0.0    0.0
29       40         1   0   0  29    0.0    0.0    0.0    0.0    0.0
...      ..       ...  ..  ..  ..    ...    ...    ...    ...    ...
1081314  40         6  43  63  34    0.0    0.0    0.0    0.0    0.0
1081315  40         6  43  63  35    0.0    0.0    0.0    0.0    0.0
1081316  40         6  43  63  36    0.0    0.0    0.0    0.0    0.0
1081317  40         6  43  63  37    0.0    0.0    0.0    0.0    0.0
1081318  40         6  43  63  38    0.0    0.0    0.0    0.0    0.0
1081319  40         6  43  63  39    0.0    0.0    0.0    0.0    0.0
1081320  40         6  43  63  40    0.0    0.0    0.0    0.0    0.0
1081321  40         6  43  63  41    0.0    0.0    0.0    0.0    0.0
1081322  40         6  43  63  42    0.0    0.0    0.0    0.0    0.0
1081323  40         6  43  63  43    0.0    0.0    0.0    0.0    0.0
1081324  40         6  43  63  44    0.0    0.0    0.0    0.0    0.0
1081325  40         6  43  63  45    0.0    0.0    0.0    0.0    0.0
1081326  40         6  43  63  46    0.0    0.0    0.0    0.0    0.0
1081327  40         6  43  63  47    0.0    0.0    0.0    0.0    0.0
1081328  40         6  43  63  48    0.0    0.0    0.0    0.0    0.0
1081329  40         6  43  63  49    0.0    0.0    0.0    0.0    0.0
1081330  40         6  43  63  50    0.0    0.0    0.0    0.0    0.0
1081331  40         6  43  63  51    0.0    0.0    0.0    0.0    0.0
1081332  40         6  43  63  52    0.0    0.0    0.0    0.0    0.0
1081333  40         6  43  63  53    0.0    0.0    0.0    0.0    0.0
1081334  40         6  43  63  54    0.0    0.0    0.0    0.0    0.0
1081335  40         6  43  63  55    0.0    0.0    0.0    0.0    0.0
1081336  40         6  43  63  56    0.0    0.0    0.0    0.0    0.0
1081337  40         6  43  63  57    0.0    0.0    0.0    0.0    0.0
1081338  40         6  43  63  58    0.0    0.0    0.0    0.0    0.0
1081339  40         6  43  63  59    0.0    0.0    0.0    0.0    0.0
1081340  40         6  43  63  60    0.0    0.0    0.0    0.0    0.0
1081341  40         6  43  63  61    0.0    0.0    0.0    0.0    0.0
1081342  40         6  43  63  62    0.0    0.0    0.0    0.0    0.0
1081343  40         6  43  63  63    0.0    0.0    0.0    0.0    0.0

[1081344 rows x 10 columns]

In [19]:
np.savetxt(save_path+"fmap_mean_40.txt", result_40.values, fmt="%s")

# Separate -ON

In [6]:
def extract_mean_separate_neg(sub_path, experiment):
    print(sub_path)
    cwd_path = sub_path+"/NIFTI/bmaps_numpy/"
    result = pd.DataFrame()
    for m in range(len(base_runs)): # mini experiment
        # Bvals
#         for l in range(2):
#             tdir = cwd_path+bp[m][l][0]+"minus"+bp[m][l][1]+"/"
#             theory_img = nib.load(tdir+"Bvals.nii")
#             theory_data = theory_img.get_data()
#             sp = theory_data.shape
#             b_data = []
            
#             neg = 0
#             if l==1:
#                 neg = 1

#             for i in range(sp[0]):
#                 for j in range(sp[1]):
#                     for k in range(sp[2]):
#                         b_data.append([experiment, m+1, i, j, k, neg, theory_data[i][j][k]])
            
#             if l==0:
#                 b_df = pd.DataFrame(b_data, columns=['exp', 'mini_exp', 'i', 'j', 'k', 'neg', 'theory'])
#             else:
#                 b_df2 = pd.DataFrame(b_data, columns=['exp', 'mini_exp', 'i', 'j', 'k', 'neg', 'theory'])

        df = pd.DataFrame()
        df2 = pd.DataFrame()
        new_df = pd.DataFrame()
        new_df2 = pd.DataFrame()
        for n in range(len(base_runs[m])): # 5 runs
            bdir = cwd_path+"base_run_"+base_runs[m][n]+"/"
            print(base_runs[m][n])

            new_data = []    
            new_data2 = [] 
            fmap_img = nib.load(bdir+"4d_fmap_Mean.nii.gz")
            fmap_data = fmap_img.get_data()
            sp = fmap_data.shape  
       
            for i in range(sp[0]):
                for j in range(sp[1]):
                    for k in range(sp[2]):
                        new_data.append([experiment, m+1, i, j, k, 0, fmap_data[i][j][k]])
                        new_data2.append([experiment, m+1, i, j, k, 1, fmap_data[i][j][k]])

            if n<=2:          
                col = "mean"+str(n)
                new_df = pd.DataFrame(new_data, columns=['exp', 'mini_exp', 'i', 'j', 'k', 'neg', col])
            if n>=2:
                col = "mean"+str(n-2)
                new_df2 = pd.DataFrame(new_data2, columns=['exp', 'mini_exp', 'i', 'j', 'k', 'neg', col])
                
            if n == 0:
                df = new_df 
            elif n<=2:
                df = df.merge(new_df, on=['exp', 'mini_exp', 'i', 'j', 'k', 'neg'], sort=False)

            if n == 2:
                df2 = new_df2
            elif n>2:
                df2 = df2.merge(new_df2, on=['exp', 'mini_exp', 'i', 'j', 'k', 'neg'], sort=False)

#         df = df.merge(b_df, on=['exp','mini_exp', 'i', 'j', 'k', 'neg'], sort=False)
#         df2 = df2.merge(b_df2, on=['exp','mini_exp', 'i', 'j', 'k', 'neg'], sort=False)
        
        result = result.append(df, ignore_index=True)
        result = result.append(df2, ignore_index=True)
    return result

In [7]:
result_40 = extract_mean_separate_neg(sub_path_40, '40')

/Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_40_Sphere/
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62

In [8]:
print(result_40.shape)

(2162688, 9)

In [10]:
1081344*2

2162688

In [9]:
result_40

        exp  mini_exp   i   j   k  neg  mean0  mean1  mean2
0        40         1   0   0   0    0    0.0    0.0    0.0
1        40         1   0   0   1    0    0.0    0.0    0.0
2        40         1   0   0   2    0    0.0    0.0    0.0
3        40         1   0   0   3    0    0.0    0.0    0.0
4        40         1   0   0   4    0    0.0    0.0    0.0
5        40         1   0   0   5    0    0.0    0.0    0.0
6        40         1   0   0   6    0    0.0    0.0    0.0
7        40         1   0   0   7    0    0.0    0.0    0.0
8        40         1   0   0   8    0    0.0    0.0    0.0
9        40         1   0   0   9    0    0.0    0.0    0.0
10       40         1   0   0  10    0    0.0    0.0    0.0
11       40         1   0   0  11    0    0.0    0.0    0.0
12       40         1   0   0  12    0    0.0    0.0    0.0
13       40         1   0   0  13    0    0.0    0.0    0.0
14       40         1   0   0  14    0    0.0    0.0    0.0
15       40         1   0   0  15    0    0.0    0.0    0.0
16       40         1   0   0  16    0    0.0    0.0    0.0
17       40         1   0   0  17    0    0.0    0.0    0.0
18       40         1   0   0  18    0    0.0    0.0    0.0
19       40         1   0   0  19    0    0.0    0.0    0.0
20       40         1   0   0  20    0    0.0    0.0    0.0
21       40         1   0   0  21    0    0.0    0.0    0.0
22       40         1   0   0  22    0    0.0    0.0    0.0
23       40         1   0   0  23    0    0.0    0.0    0.0
24       40         1   0   0  24    0    0.0    0.0    0.0
25       40         1   0   0  25    0    0.0    0.0    0.0
26       40         1   0   0  26    0    0.0    0.0    0.0
27       40         1   0   0  27    0    0.0    0.0    0.0
28       40         1   0   0  28    0    0.0    0.0    0.0
29       40         1   0   0  29    0    0.0    0.0    0.0
...      ..       ...  ..  ..  ..  ...    ...    ...    ...
2162658  40         6  43  63  34    1    0.0    0.0    0.0
2162659  40         6  43  63  35    1    0.0    0.0    0.0
2162660  40         6  43  63  36    1    0.0    0.0    0.0
2162661  40         6  43  63  37    1    0.0    0.0    0.0
2162662  40         6  43  63  38    1    0.0    0.0    0.0
2162663  40         6  43  63  39    1    0.0    0.0    0.0
2162664  40         6  43  63  40    1    0.0    0.0    0.0
2162665  40         6  43  63  41    1    0.0    0.0    0.0
2162666  40         6  43  63  42    1    0.0    0.0    0.0
2162667  40         6  43  63  43    1    0.0    0.0    0.0
2162668  40         6  43  63  44    1    0.0    0.0    0.0
2162669  40         6  43  63  45    1    0.0    0.0    0.0
2162670  40         6  43  63  46    1    0.0    0.0    0.0
2162671  40         6  43  63  47    1    0.0    0.0    0.0
2162672  40         6  43  63  48    1    0.0    0.0    0.0
2162673  40         6  43  63  49    1    0.0    0.0    0.0
2162674  40         6  43  63  50    1    0.0    0.0    0.0
2162675  40         6  43  63  51    1    0.0    0.0    0.0
2162676  40         6  43  63  52    1    0.0    0.0    0.0
2162677  40         6  43  63  53    1    0.0    0.0    0.0
2162678  40         6  43  63  54    1    0.0    0.0    0.0
2162679  40         6  43  63  55    1    0.0    0.0    0.0
2162680  40         6  43  63  56    1    0.0    0.0    0.0
2162681  40         6  43  63  57    1    0.0    0.0    0.0
2162682  40         6  43  63  58    1    0.0    0.0    0.0
2162683  40         6  43  63  59    1    0.0    0.0    0.0
2162684  40         6  43  63  60    1    0.0    0.0    0.0
2162685  40         6  43  63  61    1    0.0    0.0    0.0
2162686  40         6  43  63  62    1    0.0    0.0    0.0
2162687  40         6  43  63  63    1    0.0    0.0    0.0

[2162688 rows x 9 columns]

In [11]:
np.savetxt(save_path+"fmap_mean_neg_40.txt", result_40.values, fmt="%s")