In [1]:
import nibabel as nib
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sb
from scipy import stats
import commands

In [2]:
def get_even_num(num=63):
    runs = []
    evens = []
    j = 0
    for i in range(num):
        if (i != 0) & (i != 2):
            if i % 2 == 0:
                evens.append(str(i))
                j += 1
                if j == 5: 
                    runs.append(evens)
                    evens = []
                    j = 0
    return runs

In [33]:
data_path = "/Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/"
# data_path = "/Users/mriworkshop/Documents/TDCS/code/tdcs_thesis/data/"
save_path = data_path+"raw/"
sub_path_32 = data_path+"external/R21_32_aqueous_2mA/"
sub_path_33 = data_path+"external/R21_33_aqueous_2mA/"
# sub_path_35 = data_path+"external/R21_35_Cyl_Aqueous/"
sub_path_36 = data_path+"external/R21_36_Cyl_Aqueous_v3_simplot/"
sub_path_37 = data_path+"external/R21_37_Cyl_Aqueous/"
sub_path_38 = data_path+"external/R21_38_Cyl_Aqueous/"
tes = [2.46, 4.61, 7.09, 10.5, 15.0, 20.0, 24.5, 29.0, 33.5, 38.0, 42.5, 47.0]

# 36 to 38
base_runs = get_even_num()
bp = [['6','4'],['10','4'],['6','10']],[['16','14'],['20','14'],['16','20']],[['26','24'],['30','24'],['26','30']],[['36','34'],['40','34'],['36','40']],[['46','44'],['50','44'],['46','50']],[['56','54'],['60','54'],['56','60']]

In [4]:
base_runs

[['4', '6', '8', '10', '12'],
 ['14', '16', '18', '20', '22'],
 ['24', '26', '28', '30', '32'],
 ['34', '36', '38', '40', '42'],
 ['44', '46', '48', '50', '52'],
 ['54', '56', '58', '60', '62']]

In [5]:
bp

([['6', '4'], ['10', '4'], ['6', '10']],
 [['16', '14'], ['20', '14'], ['16', '20']],
 [['26', '24'], ['30', '24'], ['26', '30']],
 [['36', '34'], ['40', '34'], ['36', '40']],
 [['46', '44'], ['50', '44'], ['46', '50']],
 [['56', '54'], ['60', '54'], ['56', '60']])

# ROI

In [38]:
def create_roi_image(sub_path, base_runs, bp, mins):
    for n in range(len(base_runs)):
        cwd_path = sub_path+"bmaps/"
#         cwd_path = sub_path+"NIFTI/bmaps_numpy/"
        for m in range(len(bp[n])):
            tdir = cwd_path+bp[n][m][0]+"minus"+bp[n][m][1]+"/"
            print commands.getoutput("fslroi "+tdir+"4d_fmap_Mean.nii.gz "+tdir+"4d_fmap_Mean_fslroi.nii.gz "+mins[0]+" 19 "+mins[1]+" 19 "+mins[2]+" 44")

        for m in range(len(base_runs[n])):
            bdir = cwd_path+"base_run_"+base_runs[n][m]+"/"
            print commands.getoutput("fslroi "+bdir+"4d_fmap_Mean.nii.gz "+bdir+"4d_fmap_Mean_fslroi.nii.gz "+mins[0]+" 19 "+mins[1]+" 19 "+mins[2]+" 44")

In [29]:
# 32
base_runs = [['4', '6', '8', '10', '12']]
bp = [[['6','4'],['10','4'],['6','10']]]
mins = ['12', '25', '10']
create_roi_image(sub_path_32, base_runs, bp, mins)

In [30]:
# 33
base_runs = [['4', '6', '8', '10', '12'], ['14', '16', '18', '20', '22']]
bp = [['6','4'],['10','4'],['6','10']],[['16','14'],['20','14'],['16','20']]
mins = ['12', '25', '8']
create_roi_image(sub_path_33, base_runs, bp, mins)

In [34]:
# 36
base_runs = get_even_num()
bp = [['6','4'],['10','4'],['6','10']],[['16','14'],['20','14'],['16','20']],[['26','24'],['30','24'],['26','30']],[['36','34'],['40','34'],['36','40']],[['46','44'],['50','44'],['46','50']],[['56','54'],['60','54'],['56','60']]
mins = ['12', '27', '10']
create_roi_image(sub_path_36, base_runs, bp, mins)

In [39]:
# 37
base_runs = [['4', '6', '8', '10', '12'],
 ['24', '26', '28', '30', '32'],
 ['34', '36', '38', '40', '42'],
 ['44', '46', '48', '50', '52'],
 ['54', '56', '58', '60', '62']]
bp = [['6','4'],['10','4'],['6','10']],[['26','24'],['30','24'],['26','30']],[['36','34'],['40','34'],['36','40']],[['46','44'],['50','44'],['46','50']],[['56','54'],['60','54'],['56','60']]
mins = ['12', '25', '10']
create_roi_image(sub_path_37, base_runs, bp, mins)

In [37]:
# 38
base_runs = get_even_num()
bp = [['6','4'],['10','4'],['6','10']],[['16','14'],['20','14'],['16','20']],[['26','24'],['30','24'],['26','30']],[['36','34'],['40','34'],['36','40']],[['46','44'],['50','44'],['46','50']],[['56','54'],['60','54'],['56','60']]
mins = ['12', '25', '10']
create_roi_image(sub_path_38, base_runs, bp, mins)

# ROI Bvals

In [40]:
def create_roi_bvals(sub_path, base_runs, bp, mins):
    for n in range(len(base_runs)):
        cwd_path = sub_path+"bmaps/"
#         cwd_path = sub_path+"NIFTI/bmaps_numpy/"
        for m in range(len(bp[n])):
            tdir = cwd_path+bp[n][m][0]+"minus"+bp[n][m][1]+"/"
            print commands.getoutput("fslroi "+tdir+"Bvals.nii "+tdir+"Bvals_fslroi.nii "+mins[0]+" 19 "+mins[1]+" 19 "+mins[2]+" 44")

In [41]:
# 32
base_runs = [['4', '6', '8', '10', '12']]
bp = [[['6','4'],['10','4'],['6','10']]]
mins = ['12', '25', '10']
create_roi_bvals(sub_path_32, base_runs, bp, mins)

In [42]:
# 33
base_runs = [['4', '6', '8', '10', '12'], ['14', '16', '18', '20', '22']]
bp = [['6','4'],['10','4'],['6','10']],[['16','14'],['20','14'],['16','20']]
mins = ['12', '25', '8']
create_roi_bvals(sub_path_33, base_runs, bp, mins)

In [46]:
# 36
base_runs = get_even_num()
bp = [['6','4'],['10','4'],['6','10']],[['16','14'],['20','14'],['16','20']],[['26','24'],['30','24'],['26','30']],[['36','34'],['40','34'],['36','40']],[['46','44'],['50','44'],['46','50']],[['56','54'],['60','54'],['56','60']]
mins = ['12', '27', '10']
create_roi_bvals(sub_path_36, base_runs, bp, mins)

In [44]:
# 37
base_runs = [['4', '6', '8', '10', '12'],
 ['24', '26', '28', '30', '32'],
 ['34', '36', '38', '40', '42'],
 ['44', '46', '48', '50', '52'],
 ['54', '56', '58', '60', '62']]
bp = [['6','4'],['10','4'],['6','10']],[['26','24'],['30','24'],['26','30']],[['36','34'],['40','34'],['36','40']],[['46','44'],['50','44'],['46','50']],[['56','54'],['60','54'],['56','60']]
mins = ['12', '25', '10']
create_roi_bvals(sub_path_37, base_runs, bp, mins)

In [45]:
# 38
base_runs = get_even_num()
bp = [['6','4'],['10','4'],['6','10']],[['16','14'],['20','14'],['16','20']],[['26','24'],['30','24'],['26','30']],[['36','34'],['40','34'],['36','40']],[['46','44'],['50','44'],['46','50']],[['56','54'],['60','54'],['56','60']]
mins = ['12', '25', '10']
create_roi_bvals(sub_path_38, base_runs, bp, mins)

# Extract Data

## 3 attributes (separete negative)

In [47]:
def extract_mean_separate_neg(sub_path, experiment):
    print(sub_path)
    cwd_path = sub_path+"bmaps/"
    result = pd.DataFrame()
    for m in range(len(base_runs)): # mini experiment
        # Bvals
        for l in range(2):
            tdir = cwd_path+bp[m][l][0]+"minus"+bp[m][l][1]+"/"
            theory_img = nib.load(tdir+"Bvals_fslroi.nii.gz")
            theory_data = theory_img.get_data()
            sp = theory_data.shape
            b_data = []
            
            neg = 0
            if l==1:
                neg = 1

            for i in range(sp[0]):
                for j in range(sp[1]):
                    for k in range(sp[2]):
                        b_data.append([experiment, m+1, i, j, k, 2, neg, theory_data[i][j][k]])
            
            if l==0:
                b_df = pd.DataFrame(b_data, columns=['exp', 'mini_exp', 'i', 'j', 'k', 'amp', 'neg', 'theory'])
            else:
                b_df2 = pd.DataFrame(b_data, columns=['exp', 'mini_exp', 'i', 'j', 'k', 'amp', 'neg', 'theory'])

        df = pd.DataFrame()
        df2 = pd.DataFrame()
        new_df = pd.DataFrame()
        new_df2 = pd.DataFrame()
        for n in range(len(base_runs[m])): # 5 runs
            bdir = cwd_path+"base_run_"+base_runs[m][n]+"/"
            print(base_runs[m][n])

            new_data = []    
            new_data2 = [] 
            fmap_img = nib.load(bdir+"4d_fmap_Mean_fslroi.nii.gz")
            fmap_data = fmap_img.get_data()
            sp = fmap_data.shape  
       
            for i in range(sp[0]):
                for j in range(sp[1]):
                    for k in range(sp[2]):
                        new_data.append([experiment, m+1, i, j, k, 2, 0, fmap_data[i][j][k]])
                        new_data2.append([experiment, m+1, i, j, k, 2, 1, fmap_data[i][j][k]])

            if n<=2:          
                col = "mean"+str(n)
                new_df = pd.DataFrame(new_data, columns=['exp', 'mini_exp', 'i', 'j', 'k', 'amp', 'neg', col])
            if n>=2:
                col = "mean"+str(n-2)
                new_df2 = pd.DataFrame(new_data2, columns=['exp', 'mini_exp', 'i', 'j', 'k', 'amp', 'neg', col])
                
            if n == 0:
                df = new_df 
            elif n<=2:
                df = df.merge(new_df, on=['exp', 'mini_exp', 'i', 'j', 'k', 'amp', 'neg'], sort=False)

            if n == 2:
                df2 = new_df2
            elif n>2:
                df2 = df2.merge(new_df2, on=['exp', 'mini_exp', 'i', 'j', 'k', 'amp', 'neg'], sort=False)

        df = df.merge(b_df, on=['exp','mini_exp', 'i', 'j', 'k', 'amp', 'neg'], sort=False)
        df2 = df2.merge(b_df2, on=['exp','mini_exp', 'i', 'j', 'k', 'amp', 'neg'], sort=False)
        
        result = result.append(df, ignore_index=True)
        result = result.append(df2, ignore_index=True)
    return result

In [48]:
# 32
base_runs = [['4', '6', '8', '10', '12']]
bp = [[['6','4'],['10','4'],['6','10']]]
result_32 = extract_mean_separate_neg(sub_path_32, '32')

/Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_32_aqueous_2mA/
4
6
8
10
12

In [49]:
# 33
base_runs = [['4', '6', '8', '10', '12'], ['14', '16', '18', '20', '22']]
bp = [['6','4'],['10','4'],['6','10']],[['16','14'],['20','14'],['16','20']]
result_33 = extract_mean_separate_neg(sub_path_33, '33')

/Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_33_aqueous_2mA/
4
6
8
10
12
14
16
18
20
22

In [50]:
# 36 & 38
base_runs = get_even_num()
bp = [['6','4'],['10','4'],['6','10']],[['16','14'],['20','14'],['16','20']],[['26','24'],['30','24'],['26','30']],[['36','34'],['40','34'],['36','40']],[['46','44'],['50','44'],['46','50']],[['56','54'],['60','54'],['56','60']]

In [51]:
result_36 = extract_mean_separate_neg(sub_path_36, '36')
result_38 = extract_mean_separate_neg(sub_path_38, '38')

/Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_36_Cyl_Aqueous_v3_simplot/
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
/Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_38_Cyl_Aqueous/
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62

In [52]:
# 37
base_runs = [['4', '6', '8', '10', '12'],
 ['24', '26', '28', '30', '32'],
 ['34', '36', '38', '40', '42'],
 ['44', '46', '48', '50', '52'],
 ['54', '56', '58', '60', '62']]
bp = [['6','4'],['10','4'],['6','10']],[['26','24'],['30','24'],['26','30']],[['36','34'],['40','34'],['36','40']],[['46','44'],['50','44'],['46','50']],[['56','54'],['60','54'],['56','60']]
result_37 = extract_mean_separate_neg(sub_path_37, '37')

/Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_37_Cyl_Aqueous/
4
6
8
10
12
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62

In [53]:
print(result_32.shape)
print(result_33.shape)
print(result_36.shape)
print(result_37.shape)
print(result_38.shape)

(31768, 11)
(63536, 11)
(190608, 11)
(158840, 11)
(190608, 11)

In [54]:
result = result_32.append(result_33, ignore_index=True)
result = result.append(result_36, ignore_index=True)
result = result.append(result_37, ignore_index=True)
result = result.append(result_38, ignore_index=True)
result

,exp,mini_exp,i,j,k,amp,neg,mean0,mean1,mean2,theory
0,32,1,0,0,0,2,0,-467.847626,-474.438446,-490.049805,2.608974
1,32,1,0,0,1,2,0,-624.234802,-630.178467,-644.649231,2.824424
2,32,1,0,0,2,2,0,-716.909119,-724.083923,-738.119629,3.062833
3,32,1,0,0,3,2,0,-737.430176,-744.375488,-758.378723,3.327526
4,32,1,0,0,4,2,0,-717.468018,-725.066650,-738.667725,3.622561
5,32,1,0,0,5,2,0,-664.930542,-672.251892,-685.979736,3.952971
6,32,1,0,0,6,2,0,-599.134216,-606.356262,-620.125793,4.325121
7,32,1,0,0,7,2,0,-512.563110,-519.078857,-532.806335,4.747225
8,32,1,0,0,8,2,0,-417.605225,-423.989960,-438.316223,5.230128
9,32,1,0,0,9,2,0,-320.168823,-326.610748,-341.100372,5.788512
10,32,1,0,0,10,2,0,-217.105469,-222.876678,-237.597549,6.442804
11,32,1,0,0,11,2,0,-112.446899,-117.612068,-132.813675,7.222276
12,32,1,0,0,12,2,0,-12.301640,-17.339399,-33.440239,8.170268
13,32,1,0,0,13,2,0,78.819519,75.097542,57.877277,9.353257
14,32,1,0,0,14,2,0,166.334106,163.486618,144.827972,10.877214
15,32,1,0,0,15,2,0,244.590210,243.859894,223.159683,12.918038
16,32,1,0,0,16,2,0,316.241272,317.748444,294.490417,15.779174
17,32,1,0,0,17,2,0,382.871185,388.083618,360.748047,19.996826
18,32,1,0,0,18,2,0,448.573761,459.739532,426.241699,26.487646
19,32,1,0,0,19,2,0,514.774963,533.422058,492.006897,36.437054
20,32,1,0,0,20,2,0,589.211365,618.763550,565.883484,49.175610
21,32,1,0,0,21,2,0,641.831238,682.980591,618.468323,56.304222
22,32,1,0,0,22,2,0,634.363281,667.462769,610.883606,49.175610
23,32,1,0,0,23,2,0,587.876099,610.257324,563.883423,36.437054
24,32,1,0,0,24,2,0,550.166870,560.352600,526.247253,26.487646
25,32,1,0,0,25,2,0,505.252350,510.400543,481.417847,19.996826
26,32,1,0,0,26,2,0,470.728027,470.753479,446.645966,15.779174
27,32,1,0,0,27,2,0,416.614563,413.671875,393.111023,12.918038
28,32,1,0,0,28,2,0,360.404388,355.054779,335.853729,10.877214
29,32,1,0,0,29,2,0,293.560699,286.021301,269.721436,9.353257
...,...,...,...,...,...,...,...,...,...,...,...
635330,38,6,18,18,14,2,1,440.707581,422.843567,435.120636,-11.684761
635331,38,6,18,18,15,2,1,521.576721,501.302124,515.931519,-13.847374
635332,38,6,18,18,16,2,1,590.958984,567.135193,585.133789,-16.788420
635333,38,6,18,18,17,2,1,656.933350,627.210266,651.187134,-20.909285
635334,38,6,18,18,18,2,1,715.022888,678.176025,708.824768,-26.749847
635335,38,6,18,18,19,2,1,776.805786,731.070923,771.211792,-34.646912
635336,38,6,18,18,20,2,1,827.090637,771.371277,822.338318,-43.303020
635337,38,6,18,18,21,2,1,826.249084,771.317444,821.278870,-47.888023
635338,38,6,18,18,22,2,1,782.092163,737.222839,776.389832,-44.231251
635339,38,6,18,18,23,2,1,723.864563,688.197083,717.587769,-35.749107
635340,38,6,18,18,24,2,1,663.846497,635.380676,657.609619,-27.626059
635341,38,6,18,18,25,2,1,589.294617,565.962646,582.797058,-21.533604
635342,38,6,18,18,26,2,1,511.315918,490.822662,504.632721,-17.228968
635343,38,6,18,18,27,2,1,411.524750,394.167542,405.045898,-14.165751
635344,38,6,18,18,28,2,1,300.926056,285.227478,294.112000,-11.922488
635345,38,6,18,18,29,2,1,170.769867,155.834000,163.378159,-10.224492
635346,38,6,18,18,30,2,1,35.616646,21.452055,28.248489,-8.898555
635347,38,6,18,18,31,2,1,-113.429512,-126.613739,-120.807579,-7.834543
635348,38,6,18,18,32,2,1,-261.321716,-272.887421,-268.241241,-6.960824
635349,38,6,18,18,33,2,1,-411.904144,-422.261719,-418.423248,-6.229521
635350,38,6,18,18,34,2,1,-547.983765,-556.838928,-554.265564,-5.607728
635351,38,6,18,18,35,2,1,-675.123169,-683.217102,-681.106628,-5.072204
635352,38,6,18,18,36,2,1,-782.251526,-789.506653,-788.203674,-4.606101
635353,38,6,18,18,37,2,1,-871.257324,-878.522339,-877.250244,-4.196908
635354,38,6,18,18,38,2,1,-918.859253,-925.090271,-923.686279,-3.835119
635355,38,6,18,18,39,2,1,-954.100403,-959.997986,-959.053711,-3.513359
635356,38,6,18,18,40,2,1,-963.235291,-969.107910,-968.167297,-3.225791
635357,38,6,18,18,41,2,1,-1004.292725,-1009.776917,-1009.972046,-2.967721
635358,38,6,18,18,42,2,1,-1063.031128,-1067.428955,-1068.936646,-2.735306
635359,38,6,18,18,43,2,1,-1291.861206,-1298.490723,-1301.548584,-2.525362

In [55]:
result.shape

(635360, 11)

In [58]:
result[(result['i']==10) & (result['j']==10) & (result['k']==30)]

,exp,mini_exp,i,j,k,amp,neg,mean0,mean1,mean2,theory
8830,32,1,10,10,30,2,0,57.989193,56.400208,34.112900,13.160783
24714,32,1,10,10,30,2,1,34.112900,17.294117,15.446420,-13.160783
40598,33,1,10,10,30,2,0,161.170898,175.442688,162.952301,13.176155
56482,33,1,10,10,30,2,1,162.952301,148.864044,160.751328,-13.176155
72366,33,2,10,10,30,2,0,150.106125,164.249649,152.260635,13.176155
88250,33,2,10,10,30,2,1,152.260635,137.976898,152.376266,-13.176155
104134,36,1,10,10,30,2,0,47.951294,41.151360,3.792734,12.216857
120018,36,1,10,10,30,2,1,3.792734,-29.510010,-32.487389,-12.216857
135902,36,2,10,10,30,2,0,-41.324978,-43.583542,-75.195999,12.216857
151786,36,2,10,10,30,2,1,-75.195999,-102.764923,-102.349243,-12.216857
167670,36,3,10,10,30,2,0,-108.614380,-109.439316,-136.430878,12.216857
183554,36,3,10,10,30,2,1,-136.430878,-162.954346,-158.464600,-12.216857
199438,36,4,10,10,30,2,0,-163.663651,-162.062302,-187.435806,12.216857
215322,36,4,10,10,30,2,1,-187.435806,-210.726044,-204.798294,-12.216857
231206,36,5,10,10,30,2,0,-208.551285,-204.806992,-229.135849,12.216857
247090,36,5,10,10,30,2,1,-229.135849,-250.089676,-243.486343,-12.216857
262974,36,6,10,10,30,2,0,-245.997681,-241.066467,-264.719116,12.216857
278858,36,6,10,10,30,2,1,-264.719116,-284.437042,-275.587891,-12.216857
294742,37,1,10,10,30,2,0,117.207794,123.859489,103.393234,12.234269
310626,37,1,10,10,30,2,1,103.393234,86.859787,98.664398,-12.234269
326510,37,2,10,10,30,2,0,87.660728,95.453674,77.222656,12.234269
342394,37,2,10,10,30,2,1,77.222656,63.034306,75.509232,-12.234269
358278,37,3,10,10,30,2,0,76.029366,83.800819,66.183723,12.234269
374162,37,3,10,10,30,2,1,66.183723,52.200809,65.350082,-12.234269
390046,37,4,10,10,30,2,0,65.070297,73.560997,56.926571,12.234269
405930,37,4,10,10,30,2,1,56.926571,42.518497,54.841171,-12.234269
421814,37,5,10,10,30,2,0,55.859608,64.760361,47.742073,12.234269
437698,37,5,10,10,30,2,1,47.742073,33.483727,46.802307,-12.234269
453582,38,1,10,10,30,2,0,126.897568,134.921768,112.268593,13.272241
469466,38,1,10,10,30,2,1,112.268593,93.995041,105.709831,-13.272241
485350,38,2,10,10,30,2,0,102.521439,109.808914,94.228195,13.272241
501234,38,2,10,10,30,2,1,94.228195,78.555794,93.206680,-13.272241
517118,38,3,10,10,30,2,0,109.032478,118.749062,105.373688,13.272241
533002,38,3,10,10,30,2,1,105.373688,92.813316,103.703163,-13.272241
548886,38,4,10,10,30,2,0,120.155251,130.760605,118.370766,13.272241
564770,38,4,10,10,30,2,1,118.370766,104.086212,114.500961,-13.272241
580654,38,5,10,10,30,2,0,107.421234,120.547806,109.634163,13.272241
596538,38,5,10,10,30,2,1,109.634163,93.124924,102.175346,-13.272241
612422,38,6,10,10,30,2,0,122.875153,137.814911,124.335861,13.272241
628306,38,6,10,10,30,2,1,124.335861,106.832321,118.113297,-13.272241

In [59]:
np.savetxt(save_path+"fmap_mean_roi_32to38.txt", result.values, fmt="%s")