In [1]:
import nibabel as nib
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sb
from scipy import stats
import commands

In [5]:
def get_even_num(num=93):
    runs = []
    evens = []
    j = 0
    for i in range(num):
        if (i != 0) & (i != 2):
            if i % 2 == 0:
                evens.append(str(i))
                j += 1
                if j == 5: 
                    runs.append(evens)
                    evens = []
                    j = 0
    return runs

In [38]:
def get_minus_num(base_runs):
    li = []
    for i in range(len(base_runs)):
        li.append([[base_runs[i][1],base_runs[i][0]], [base_runs[i][3],base_runs[i][0]], [base_runs[i][1],base_runs[i][3]]])
    return li

In [23]:
data_path = "/Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/"
# data_path = "/Users/mriworkshop/Documents/TDCS/code/tdcs_thesis/data/"
save_path = data_path+"raw/"
sub_path_42 = data_path+"external/R21_42_SphereProto3/"
sub_path_43 = data_path+"external/R21_43_Sphere_Proto3/"
sub_path_44 = data_path+"external/R21_44_Sphere_Proto3/"
sub_path_45 = data_path+"external/R21_45_Sphere_Proto3/"
# tes = [2.46, 4.61, 7.09, 10.5, 15.0, 20.0, 24.5, 29.0, 33.5, 38.0, 42.5, 47.0]

base_runs = get_even_num()
bp = get_minus_num(base_runs)

In [32]:
base_runs

[['4', '6', '8', '10', '12'],
 ['14', '16', '18', '20', '22'],
 ['24', '26', '28', '30', '32'],
 ['34', '36', '38', '40', '42'],
 ['44', '46', '48', '50', '52'],
 ['54', '56', '58', '60', '62'],
 ['64', '66', '68', '70', '72'],
 ['74', '76', '78', '80', '82'],
 ['84', '86', '88', '90', '92']]

In [39]:
bp

[[['6', '4'], ['10', '4'], ['6', '10']],
 [['16', '14'], ['20', '14'], ['16', '20']],
 [['26', '24'], ['30', '24'], ['26', '30']],
 [['36', '34'], ['40', '34'], ['36', '40']],
 [['46', '44'], ['50', '44'], ['46', '50']],
 [['56', '54'], ['60', '54'], ['56', '60']],
 [['66', '64'], ['70', '64'], ['66', '70']],
 [['76', '74'], ['80', '74'], ['76', '80']],
 [['86', '84'], ['90', '84'], ['86', '90']]]

# ROI

In [95]:
def create_roi_image(sub_path, base_runs, bp, mins):
    for n in range(len(base_runs)):
        cwd_path = sub_path+"bmaps/"
#         cwd_path = sub_path+"NIFTI/bmaps_numpy/"
        for m in range(2):
            tdir = cwd_path+bp[n][m][0]+"minus"+bp[n][m][1]+"/"
            print commands.getoutput("fslroi "+tdir+"4d_fmap_Mean.nii.gz "+tdir+"4d_fmap_Mean_fslroi.nii.gz "+mins[0]+" 20 "+mins[1]+" 20 "+mins[2]+" 20")
            print commands.getoutput("fslroi "+tdir+"Bfieldz_fmap.nii.gz "+tdir+"Bfieldz_fmap_fslroi.nii.gz "+mins[0]+" 20 "+mins[1]+" 20 "+mins[2]+" 20")
            print commands.getoutput("fslroi "+tdir+"detrend1.nii.gz "+tdir+"detrend1_fslroi.nii.gz "+mins[0]+" 20 "+mins[1]+" 20 "+mins[2]+" 20")

        for m in range(len(base_runs[n])):
            bdir = cwd_path+"base_run_"+base_runs[n][m]+"/"
            print commands.getoutput("fslroi "+bdir+"4d_fmap_Mean.nii.gz "+bdir+"4d_fmap_Mean_fslroi.nii.gz "+mins[0]+" 20 "+mins[1]+" 20 "+mins[2]+" 20")

In [30]:
# 42
br = [['66', '68', '70', '72', '74'],
 ['76', '78', '80', '82', '84'],
 ['86', '88', '90', '92', '94']]
bp = get_minus_num(br)
mins = ['11', '19', '21']
create_roi_image(sub_path_42, br, bp, mins)

Image Exception : #63 :: No image files match: /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_42_SphereProto3/bmaps/base_run_70/4d_fmap_Mean
No image files match: /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_42_SphereProto3/bmaps/base_run_70/4d_fmap_Mean


Image Exception : #63 :: No image files match: /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_42_SphereProto3/bmaps/base_run_76/4d_fmap_Mean
No image files match: /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_42_SphereProto3/bmaps/base_run_76/4d_fmap_Mean
Image Exception : #63 :: No image files match: /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_42_SphereProto3/bmaps/base_run_78/4d_fmap_Mean
No image files match: /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_42_SphereProto3/bmaps/base_run_78/4d_fmap_Mean

Image Exception : #63 :: No image files match: /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_42_SphereProto3/bmaps/base_run_82/4d_fmap_Mean
No image files match: /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_42_SphereProto3/bmaps/base_run_82/4d_fmap_Mean
Image Exception : #63 :: No image files match: /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_42_SphereProto3/bmaps/base_run_84/4d_fmap_Mean
No image files match: /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_42_SphereProto3/bmaps/base_run_84/4d_fmap_Mean

In [58]:
base_runs[3:5]+[base_runs[8]]

[['34', '36', '38', '40', '42'],
 ['44', '46', '48', '50', '52'],
 ['84', '86', '88', '90', '92']]

In [96]:
# 43
br = base_runs[3:5]+[base_runs[8]]
bp = get_minus_num(br)
mins = ['11', '28', '21']
create_roi_image(sub_path_43, br, bp, mins)

Image Exception : #63 :: No image files match: /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_43_Sphere_Proto3/bmaps/36minus34/detrend1
No image files match: /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_43_Sphere_Proto3/bmaps/36minus34/detrend1


Image Exception : #63 :: No image files match: /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_43_Sphere_Proto3/bmaps/40minus34/detrend1
No image files match: /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_43_Sphere_Proto3/bmaps/40minus34/detrend1







Image Exception : #63 :: No image files match: /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_43_Sphere_Proto3/bmaps/46minus44/detrend1
No image files match: /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_43_Sphere_Proto3/bmaps/46minus44/detrend1


Image Exception : #63 :: No image files match: /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_43_Sphere_Proto3/bmaps/50minus44/detrend1
No image files match: /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_43_Sphere_Proto3/bmaps/50minus44/detrend1







Image Exception : #63 :: No image files match: /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_43_Sphere_Proto3/bmaps/86minus84/detrend1
No image files match: /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_43_Sphere_Proto3/bmaps/86minus84/detrend1


Image Exception : #63 :: No image files match: /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_43_Sphere_Proto3/bmaps/90minus84/detrend1
No image files match: /Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_43_Sphere_Proto3/bmaps/90minus84/detrend1

In [59]:
base_runs[3:6]

[['34', '36', '38', '40', '42'],
 ['44', '46', '48', '50', '52'],
 ['54', '56', '58', '60', '62']]

In [97]:
# 44
br = base_runs[3:6]
bp = get_minus_num(br)
mins = ['11', '28', '21']
create_roi_image(sub_path_44, br, bp, mins)

In [52]:
base_runs[0:3]

[['4', '6', '8', '10', '12'],
 ['14', '16', '18', '20', '22'],
 ['24', '26', '28', '30', '32']]

In [34]:
# 45
br = base_runs[0:3]
bp = get_minus_num(br)
mins = ['10', '28', '21']
create_roi_image(sub_path_44, br, bp, mins)

# Extract Data

## 3 attributes (separete negative)

In [87]:
def extract_mean_separate_neg(sub_path, experiment, br, bp):
    print(sub_path)
    cwd_path = sub_path+"bmaps/"
    result = pd.DataFrame()
    for m in range(len(br)): # mini experiment
        # Bvals
        for l in range(2):
            tdir = cwd_path+bp[m][l][0]+"minus"+bp[m][l][1]+"/"
            theory_img = nib.load(tdir+"Bfieldz_fmap_fslroi.nii.gz")
            theory_data = theory_img.get_data()
            sp = theory_data.shape
            b_data = []
            
            neg = 0
            if l==1:
                neg = 1

            for i in range(sp[0]):
                for j in range(sp[1]):
                    for k in range(sp[2]):
                        b_data.append([experiment, m+1, i, j, k, 2, neg, theory_data[i][j][k]])
            
            if l==0:
                b_df = pd.DataFrame(b_data, columns=['exp', 'mini_exp', 'i', 'j', 'k', 'amp', 'neg', 'theory'])
            else:
                b_df2 = pd.DataFrame(b_data, columns=['exp', 'mini_exp', 'i', 'j', 'k', 'amp', 'neg', 'theory'])
                
            detrend_img = nib.load(tdir+"detrend1_fslroi.nii.gz")
            detrend_data = detrend_img.get_data()
            sp = detrend_data.shape
            d_data = []

            neg = 0
            if l==1:
                neg = 1

            for i in range(sp[0]):
                for j in range(sp[1]):
                    for k in range(sp[2]):
                        d_data.append([experiment, m+1, i, j, k, 2, neg, detrend_data[i][j][k]])

            if l==0:
                d_df = pd.DataFrame(d_data, columns=['exp', 'mini_exp', 'i', 'j', 'k', 'amp', 'neg', 'detrend'])
            else:
                d_df2 = pd.DataFrame(d_data, columns=['exp', 'mini_exp', 'i', 'j', 'k', 'amp', 'neg', 'detrend'])

        df = pd.DataFrame()
        df2 = pd.DataFrame()
        new_df = pd.DataFrame()
        new_df2 = pd.DataFrame()
        for n in range(len(br[m])): # 5 runs
            bdir = cwd_path+"base_run_"+br[m][n]+"/"
            print(br[m][n])

            new_data = []    
            new_data2 = [] 
            fmap_img = nib.load(bdir+"4d_fmap_Mean_fslroi.nii.gz")
            fmap_data = fmap_img.get_data()
            sp = fmap_data.shape  
       
            for i in range(sp[0]):
                for j in range(sp[1]):
                    for k in range(sp[2]):
                        new_data.append([experiment, m+1, i, j, k, 2, 0, fmap_data[i][j][k]])
                        new_data2.append([experiment, m+1, i, j, k, 2, 1, fmap_data[i][j][k]])

            if n<=2:          
                col = "mean"+str(n)
                new_df = pd.DataFrame(new_data, columns=['exp', 'mini_exp', 'i', 'j', 'k', 'amp', 'neg', col])
            if n>=2:
                col = "mean"+str(n-2)
                new_df2 = pd.DataFrame(new_data2, columns=['exp', 'mini_exp', 'i', 'j', 'k', 'amp', 'neg', col])
                
            if n == 0:
                df = new_df 
            elif n<=2:
                df = df.merge(new_df, on=['exp', 'mini_exp', 'i', 'j', 'k', 'amp', 'neg'], sort=False)

            if n == 2:
                df2 = new_df2
            elif n>2:
                df2 = df2.merge(new_df2, on=['exp', 'mini_exp', 'i', 'j', 'k', 'amp', 'neg'], sort=False)

        df = df.merge(b_df, on=['exp','mini_exp', 'i', 'j', 'k', 'amp', 'neg'], sort=False)
        df2 = df2.merge(b_df2, on=['exp','mini_exp', 'i', 'j', 'k', 'amp', 'neg'], sort=False)
        
        df = df.merge(d_df, on=['exp','mini_exp', 'i', 'j', 'k', 'amp', 'neg'], sort=False)
        df2 = df2.merge(d_df2, on=['exp','mini_exp', 'i', 'j', 'k', 'amp', 'neg'], sort=False)
        
        result = result.append(df, ignore_index=True)
        result = result.append(df2, ignore_index=True)
    return result

Create Bvals before executing below

In [88]:
# 43
br = base_runs[3:5]+[base_runs[8]]
bp = get_minus_num(br)
result_43 = extract_mean_separate_neg(sub_path_43, '43', br, bp)

/Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_43_Sphere_Proto3/
34
36
38
40
42
44
46
48
50
52
84
86
88
90
92

In [89]:
# 44
br = base_runs[3:6]
bp = get_minus_num(br)
result_44 = extract_mean_separate_neg(sub_path_44, '44', br, bp)

/Users/chikakoolsen/opt/python/thesis/code/tdcs_thesis/data/external/R21_44_Sphere_Proto3/
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62

In [90]:
print(result_43.shape)
print(result_44.shape)
# print(result_45.shape)

(48000, 12)
(48000, 12)

In [91]:
result = result_43.append(result_44, ignore_index=True)
# result = result.append(result_45, ignore_index=True)
result

,exp,mini_exp,i,j,k,amp,neg,mean0,mean1,mean2,theory,detrend
0,43,1,0,0,0,2,0,123.692169,128.834305,127.897308,3.309486,2.431725
1,43,1,0,0,1,2,0,99.720467,105.151962,103.141129,3.425290,2.790901
2,43,1,0,0,2,2,0,82.686668,88.002533,86.484604,3.540494,2.648407
3,43,1,0,0,3,2,0,68.081421,73.930878,71.451736,3.653013,3.106575
4,43,1,0,0,4,2,0,60.588898,66.726860,64.175850,3.759392,3.207462
5,43,1,0,0,5,2,0,54.294689,60.407608,57.918579,3.858539,3.160675
6,43,1,0,0,6,2,0,53.232323,59.013420,56.372181,3.947371,3.035511
7,43,1,0,0,7,2,0,50.347462,56.140110,53.149918,4.019993,3.139965
8,43,1,0,0,8,2,0,50.899040,56.624580,54.197483,4.063707,3.016800
9,43,1,0,0,9,2,0,48.941917,54.939228,52.297588,4.081764,3.150883
10,43,1,0,0,10,2,0,49.743134,54.877659,52.515026,4.073649,2.700096
11,43,1,0,0,11,2,0,47.658382,53.092598,50.468922,4.042266,2.836418
12,43,1,0,0,12,2,0,49.675201,54.777542,52.212696,3.993905,2.669003
13,43,1,0,0,13,2,0,50.633358,55.999641,53.242771,3.926860,2.870186
14,43,1,0,0,14,2,0,67.755081,73.716209,71.296738,3.843207,3.012627
15,43,1,0,0,15,2,0,97.136848,103.284698,100.611252,3.742548,3.210236
16,43,1,0,0,16,2,0,145.072723,151.414474,149.477722,3.625727,3.191879
17,43,1,0,0,17,2,0,201.915100,208.227097,207.634216,3.503705,2.925781
18,43,1,0,0,18,2,0,261.129669,266.622284,266.138245,3.380814,2.495972
19,43,1,0,0,19,2,0,347.440948,353.071503,351.820984,3.256448,2.699982
20,43,1,0,1,0,2,0,129.758560,134.104355,133.963699,3.085067,1.893921
21,43,1,0,1,1,2,0,108.386009,113.517075,112.507339,3.202578,2.417725
22,43,1,0,1,2,2,0,89.951859,95.152046,93.370651,3.322071,2.606506
23,43,1,0,1,3,2,0,79.644066,85.264252,83.177666,3.440577,2.832527
24,43,1,0,1,4,2,0,70.706718,76.002991,74.100403,3.553298,2.651131
25,43,1,0,1,5,2,0,66.054573,71.284523,69.465347,3.659854,2.605545
26,43,1,0,1,6,2,0,63.007954,68.822929,66.426414,3.752893,2.980896
27,43,1,0,1,7,2,0,63.155392,69.468246,66.873482,3.828508,3.257202
28,43,1,0,1,8,2,0,63.927055,69.061218,66.846420,3.880893,2.625679
29,43,1,0,1,9,2,0,65.683067,71.121208,68.064713,3.903174,2.989372
...,...,...,...,...,...,...,...,...,...,...,...,...
95970,44,3,19,18,10,2,1,59.440826,63.026901,59.063782,3.334958,3.372696
95971,44,3,19,18,11,2,1,59.856430,64.009972,59.798019,3.284237,3.609924
95972,44,3,19,18,12,2,1,62.176163,66.421989,61.416069,3.218331,3.977959
95973,44,3,19,18,13,2,1,69.604637,73.597687,68.555664,3.138554,3.894722
95974,44,3,19,18,14,2,1,67.529701,71.852158,66.999695,3.047060,3.901466
95975,44,3,19,18,15,2,1,64.382965,68.704544,64.061905,2.949384,3.772964
95976,44,3,19,18,16,2,1,50.827789,56.154846,50.818722,2.849400,4.304871
95977,44,3,19,18,17,2,1,36.237854,41.022842,35.903320,2.750165,4.112324
95978,44,3,19,18,18,2,1,14.049860,18.934151,13.865070,2.650543,4.098246
95979,44,3,19,18,19,2,1,-5.414487,-0.459146,-5.485337,2.552694,4.066728
95980,44,3,19,19,0,2,1,-135.560074,-131.992340,-135.377808,3.084289,3.002441
95981,44,3,19,19,1,2,1,-78.673828,-74.347473,-78.671204,3.182399,3.556923
95982,44,3,19,19,2,2,1,-30.929161,-26.906765,-31.795069,3.277380,3.752962
95983,44,3,19,19,3,2,1,12.917467,16.775707,12.559814,3.361893,3.371207
95984,44,3,19,19,4,2,1,48.974007,52.689545,48.473656,3.436073,3.401085
95985,44,3,19,19,5,2,1,71.898613,75.964409,72.389030,3.498439,3.226967
95986,44,3,19,19,6,2,1,81.830963,86.346909,82.135773,3.545120,3.615921
95987,44,3,19,19,7,2,1,86.876572,91.199013,86.557571,3.575900,3.807640
95988,44,3,19,19,8,2,1,81.408096,86.002724,81.058128,3.588969,4.002953
95989,44,3,19,19,9,2,1,74.294907,79.130676,73.702873,3.582610,4.288422
95990,44,3,19,19,10,2,1,64.744278,69.632462,64.377945,3.553309,4.228310
95991,44,3,19,19,11,2,1,66.156479,70.683128,66.083443,3.500091,3.872574
95992,44,3,19,19,12,2,1,77.652443,82.074188,77.636986,3.434692,3.825470
95993,44,3,19,19,13,2,1,87.573112,91.600243,86.707253,3.360415,3.902946
95994,44,3,19,19,14,2,1,97.144211,101.924004,96.856606,3.274809,4.131355
95995,44,3,19,19,15,2,1,96.087486,101.054405,96.166145,3.181252,4.042931
95996,44,3,19,19,16,2,1,83.972588,89.265335,84.319496,3.083541,4.130562
95997,44,3,19,19,17,2,1,63.528229,69.086761,63.926357,2.984341,4.356812
95998,44,3,19,19,18,2,1,39.693642,45.529270,40.033745,2.882783,4.590672
95999,44,3,19,19,19,2,1,25.759155,31.273212,26.568584,2.783618,4.122089

In [92]:
result.shape

(96000, 12)

In [93]:
result[(result['i']==12) & (result['j']==1) & (result['k']==10)]

,exp,mini_exp,i,j,k,amp,neg,mean0,mean1,mean2,theory,detrend
4830,43,1,12,1,10,2,0,16.311316,20.897245,18.838100,2.569031,2.090837
12830,43,1,12,1,10,2,1,18.838100,22.450878,24.704678,-2.568843,-0.023602
20830,43,2,12,1,10,2,0,27.728964,30.963011,30.779463,2.569031,0.842682
28830,43,2,12,1,10,2,1,30.779463,35.839478,35.339111,-2.568843,1.699795
36830,43,3,12,1,10,2,0,-49.869022,-47.355843,-47.000088,2.569031,0.592464
44830,43,3,12,1,10,2,1,-47.000088,-43.939281,-41.184082,-2.568843,-0.148262
52830,44,1,12,1,10,2,0,-25.231016,-23.146566,-24.258320,2.569031,1.317064
60830,44,1,12,1,10,2,1,-24.258320,-25.755909,-23.898773,-2.568843,-1.303307
68830,44,2,12,1,10,2,0,-20.432201,-19.565550,-22.406239,2.569031,1.372707
76830,44,2,12,1,10,2,1,-22.406239,-24.144655,-22.160332,-2.568843,-1.599323
84830,44,3,12,1,10,2,0,-19.323147,-18.756927,-20.672554,2.569031,0.912043
92830,44,3,12,1,10,2,1,-20.672554,-21.781219,-20.494562,-2.568843,-1.038824

In [94]:
np.savetxt(save_path+"fmap_mean_roi_43_44.txt", result.values, fmt="%s")